version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      # kodiak `merge.automerge_label`
      - "automerge"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    groups:
      cargo-security:
        applies-to: security-updates
        patterns: ["*"]
      cargo-minor-patch:
        applies-to: version-updates
        patterns: ["*"]
        update-types: ["minor", "patch"]

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      # kodiak `merge.automerge_label`
      - "automerge"
    groups:
      github-actions:
        patterns: ["*"]

  - package-ecosystem: "npm"
    directories:
      - "/flipt-client-js"
      - "/flipt-client-react"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      # kodiak `merge.automerge_label`
      - "automerge"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    groups:
      npm-security:
        applies-to: security-updates
        patterns: ["*"]
      npm-minor-patch:
        applies-to: version-updates
        patterns: ["*"]
        update-types: ["minor", "patch"]

  - package-ecosystem: "nuget"
    directory: "/flipt-client-csharp"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      # kodiak `merge.automerge_label`
      - "automerge"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    groups:
      nuget-security:
        applies-to: security-updates
        patterns: ["*"]
      nuget-minor-patch:
        applies-to: version-updates
        patterns: ["*"]
        update-types: ["minor", "patch"]

  - package-ecosystem: "pub"
    directory: "/flipt-client-dart"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      # kodiak `merge.automerge_label`
      - "automerge"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    groups:
      pub-security:
        applies-to: security-updates
        patterns: ["*"]
      pub-minor-patch:
        applies-to: version-updates
        patterns: ["*"]
        update-types: ["minor", "patch"]

  - package-ecosystem: "gomod"
    directory: "/flipt-client-go"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      # kodiak `merge.automerge_label`
      - "automerge"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    groups:
      gomod-security:
        applies-to: security-updates
        patterns: ["*"]
      gomod-minor-patch:
        applies-to: version-updates
        patterns: ["*"]
        update-types: ["minor", "patch"]

  - package-ecosystem: "gradle"
    directories:
      - "/flipt-client-java"
      - "/flipt-client-kotlin-android"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      # kodiak `merge.automerge_label`
      - "automerge"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    groups:
      gradle-security:
        applies-to: security-updates
        patterns: ["*"]
      gradle-minor-patch:
        applies-to: version-updates
        patterns: ["*"]
        update-types: ["minor", "patch"]

  - package-ecosystem: "pip"
    directory: "/flipt-client-python"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      # kodiak `merge.automerge_label`
      - "automerge"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    groups:
      pip-security:
        applies-to: security-updates
        patterns: ["*"]
      pip-minor-patch:
        applies-to: version-updates
        patterns: ["*"]
        update-types: ["minor", "patch"]

  - package-ecosystem: "bundler"
    directory: "/flipt-client-ruby"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      # kodiak `merge.automerge_label`
      - "automerge"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    groups:
      bundler-security:
        applies-to: security-updates
        patterns: ["*"]
      bundler-minor-patch:
        applies-to: version-updates
        patterns: ["*"]
        update-types: ["minor", "patch"]
