[target."x86_64-unknown-linux-musl"]
image.name = "alpine:edge"
image.toolchain = ["x86_64-unknown-linux-musl"]
pre-build = ["apk add --no-cache gcc pkgconf musl-dev"]

[target."aarch64-unknown-linux-musl"]
image.name = "alpine:edge"
image.toolchain = ["aarch64-unknown-linux-musl"]
pre-build = ["apk add --no-cache gcc pkgconf musl-dev"]
