[tools]
go = "1.25"
golangci-lint = "2.1.6"

[tasks.lint]
description = "Run Go lint checks"
run = "touch ext/flipt_engine_wasm.wasm && golangci-lint run --timeout=5m"

[tasks.fmt]
description = "Format Go source"
run = "go fmt ./..."
