go: {
  shape: image
  icon: https://icon.icepanel.io/Technology/svg/Go.svg
}

ruby: {
  shape: image
  icon: https://icon.icepanel.io/Technology/svg/Ruby.svg
}

python: {
  shape: image
  icon: https://icon.icepanel.io/Technology/svg/Python.svg
}

typescript: {
  shape: image
  icon: https://icon.icepanel.io/Technology/svg/TypeScript.svg
}

flipt-engine-ffi: {
  shape: square
  rust: {
    shape: image
    icon: https://icon.icepanel.io/Technology/svg/Rust.svg
  }
}

flipt-service: {
  shape: square
  flipt: {
    shape: image
    icon: ./flipt.svg
  }
}

go <-> flipt-engine-ffi
ruby <-> flipt-engine-ffi
python <-> flipt-engine-ffi
typescript <-> flipt-engine-ffi

flipt-engine-ffi <-> flipt-service: Evaluation State Sync {
  style: {
    opacity: 0.9
    stroke-dash: 3
    shadow: true
  }
}
