csharp: {
  shape: image
  icon: ./icons/csharp.svg
}

ruby: {
  shape: image
  icon: ./icons/ruby.svg
}

python: {
  shape: image
  icon: ./icons/python.svg
}

java: {
  shape: image
  icon: ./icons/java.svg
}

flipt-engine-ffi: {
  shape: square
  rust: {
    shape: image
    icon: ./icons/rust.svg
  }
}

flipt-service: {
  shape: square
  flipt: {
    shape: image
    icon: ./icons/flipt.svg
  }
}

csharp <-> flipt-engine-ffi
ruby <-> flipt-engine-ffi
python <-> flipt-engine-ffi
java <-> flipt-engine-ffi

flipt-engine-ffi <-> flipt-service: Evaluation State Sync {
  style: {
    opacity: 0.9
    stroke-dash: 3
    shadow: true
  }
}
