inherit_from: .rubocop_todo.yml

Lint/MissingSuper:
  Enabled: false

Lint/UselessAssignment:
  Enabled: false

Metrics/BlockLength:
  Max: 35
  Exclude:
    - "spec/**/*"
    - "test/**/*"

Metrics/ClassLength:
  Max: 200
  Exclude:
    - "spec/**/*"
    - "test/**/*"

Metrics/MethodLength:
  Max: 50
  Exclude:
    - "spec/**/*"
    - "test/**/*"

Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Layout/LineLength:
  Exclude:
    - "spec/**/*"
    - "test/**/*"

Style/Documentation:
  Exclude:
    - "spec/**/*"
    - "test/**/*"

Style/IfUnlessModifier:
  Enabled: false
