inherit_from: .rubocop_todo.yml

Lint/UselessAssignment:
  Enabled: false

Metrics/BlockLength:
  Max: 35
  Exclude:
    - "spec/**/*"
    - "test/**/*"

Layout/LineLength:
  Exclude:
    - "spec/**/*"
    - "test/**/*"

Style/Documentation:
  Exclude:
    - "spec/**/*"
    - "test/**/*"
