# frozen_string_literal: true

source 'https://rubygems.org'

# Specify your gem's dependencies in flipt-client-ruby.gemspec
gemspec

gem 'ffi', '~> 1.17'
gem 'rake', '~> 13.4'

group :development do
  gem 'bundler', '~> 2.0'
  gem 'rspec', '~> 3.0'
  gem 'rubocop', '~> 1.86', require: false
end
