# frozen_string_literal: true

source 'https://rubygems.org'

# Specify your gem's dependencies in flipt-client-ruby.gemspec
gemspec

gem 'ffi', '~> 1.16'
gem 'rake', '~> 12.0'

group :development do
  gem 'bundler', '~> 2.0'
  gem 'rubocop', require: false
end
