name: flipt_client_ios
version: 0.1.0
description: 'Flipt Client Evaluation SDK for iOS'
homepage: https://flipt.io

environment:
  flutter: '>=1.20.0'
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  ffi: ^2.0.1
  json_annotation: ^4.9.0
  path: ^1.9.0

dev_dependencies:
  build_runner: ^2.3.3
  ffigen: '>=9.0.0 <20.0.0'
  json_serializable: ^6.6.2
  lints: '>=4.0.0 <7.0.0'
  test: ^1.21.0

flutter:
  plugin:
    platforms:
      ios:
        ffiPlugin: true
        pluginClass: FliptClient