included:
  - Sources
  - Tests

excluded:
  - .build
  - Package.swift

opt_in_rules:
  - empty_count
  - empty_string
  - force_unwrapping
  - implicitly_unwrapped_optional
  - legacy_random
  - let_var_whitespace
  - multiline_parameters
  - operator_usage_whitespace
  - overridden_super_call
  - private_outlet
  - prohibited_super_call
  - redundant_nil_coalescing
  - sorted_imports
  - toggle_bool
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces

disabled_rules:
  - trailing_whitespace
  - line_length
  - opening_brace

identifier_name:
  min_length: 2
  allowed_symbols: ["_"]
  validates_start_with_lowercase:
    error: true
  excluded:
    - id
    - up
    - x
    - y

type_name:
  min_length: 3
  max_length: 50

function_parameter_count:
  warning: 6
  error: 8

cyclomatic_complexity:
  warning: 15
  error: 25

file_length:
  warning: 500
  error: 1000

type_body_length:
  warning: 300
  error: 500
