name: Build Rust Engine
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        platform:
          - name: Linux-x86_64
            target: x86_64-unknown-linux-gnu
          - name: Linux-arm64
            target: aarch64-unknown-linux-gnu
          # - name: Windows-x86_64
          #   target: x86_64-pc-windows-msvc
          # - name: Apple-x86_64
          #   target: x86_64-apple-darwin
          - name: Apple-arm64
            target: aarch64-apple-darwin

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Rust ${{ matrix.platform.name }}
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.platform.target }}
          override: true

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-${{ matrix.platform.target}}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Build Rust ${{ matrix.platform.name }}
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --target ${{ matrix.platform.target }} --release
          use-cross: true

      - uses: actions/upload-artifact@v4
        with:
          name: fliptengine-${{ matrix.platform.name }}
          path: |
            target/${{ matrix.platform.target }}/release/libfliptengine.*
            target/${{ matrix.platform.target }}/release/flipt_engine.h
          retention-days: 5
