name: Package Rust Engine
on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        platform:
          - name: Linux-x86_64
            os: ubuntu-latest
            use_cross: false
            target: x86_64-unknown-linux-gnu
          - name: Linux-arm64
            os: ubuntu-latest
            target: aarch64-unknown-linux-gnu
            use_cross: true
          - name: Darwin-arm64
            os: macos-latest
            target: aarch64-apple-darwin
            use_cross: false

    runs-on: ${{ matrix.platform.os }}
    steps:
      - uses: actions/checkout@v3

      - name: Install Rust ${{ matrix.platform.name }}
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.platform.target }}
          override: true

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-${{ matrix.platform.target}}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Build Rust ${{ matrix.platform.name }}
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --target ${{ matrix.platform.target }} --release
          use-cross: ${{ matrix.platform.use_cross }}

      - uses: actions/upload-artifact@v4
        with:
          name: fliptengine-${{ matrix.platform.name }}
          path: |
            target/${{ matrix.platform.target }}/release/libfliptengine.*
            target/${{ matrix.platform.target }}/release/flipt_engine.h
          retention-days: 5
