name: Lint SDKs
on:
  pull_request:
    branches-ignore:
      - release/*

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

env:
  MISE_EXPERIMENTAL: "1"

jobs:
  lint:
    name: Lint ${{ matrix.sdk }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - sdk: flipt-client-python
            os: ubuntu-latest
          - sdk: flipt-client-react
            os: ubuntu-latest
          - sdk: flipt-client-js
            os: ubuntu-latest
          - sdk: flipt-client-java
            os: ubuntu-latest
          - sdk: flipt-client-ruby
            os: ubuntu-latest
          - sdk: flipt-client-csharp
            os: ubuntu-latest
          - sdk: flipt-client-kotlin-android
            os: ubuntu-latest
          - sdk: flipt-client-dart
            os: ubuntu-latest
          - sdk: flipt-client-go
            os: ubuntu-latest
          - sdk: flipt-client-swift
            os: macos-latest
    steps:
      - name: Checkout Sources
        uses: actions/checkout@v6

      - name: Setup mise
        uses: jdx/mise-action@v4
        with:
          working_directory: ${{ matrix.sdk }}

      - name: Lint
        working-directory: ${{ matrix.sdk }}
        run: mise run lint
