name: Package Go SDK
on:
  push:
    tags:
      - "flipt-client-go-**"
      - "flipt-client-go-musl-**"

permissions:
  contents: write
  id-token: write

jobs:
  build:
    uses: ./.github/workflows/package-ffi-sdks.yml
    with:
      sdks: ${{ startsWith(github.ref, 'refs/tags/flipt-client-go-musl-') && 'go-musl' || 'go' }}
      tag: ${{ github.ref }}
    secrets: inherit
