name: Package C# SDK
on:
  push:
    tags: ["flipt-client-csharp-**"]

permissions:
  contents: write
  id-token: write

env:
  NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}

jobs:
  build:
    uses: ./.github/workflows/package-ffi-sdks.yml
    with:
      sdks: csharp
    secrets: inherit
