name: Package Go SDK
on:
  push:
    tags:
      - "flipt-client-go-**"

permissions:
  contents: write
  id-token: write

jobs:
  build:
    uses: ./.github/workflows/package-wasm-sdks.yml
    with:
      sdks: "go"
      tag: ${{ github.ref }}
    secrets: inherit
