name: Package Go SDK
on:
  push:
    tags: ["flipt-client-go-**"]

permissions:
  contents: write

jobs:
  build:
    uses: ./.github/workflows/package-ffi-sdks.yml
    with:
      sdks: go,go-musl
      engine-tag: "latest"
      tag: ${{ github.ref }}
    secrets: inherit
