name: Package React SDK
on:
  push:
    tags: ["flipt-client-react-**"]

permissions:
  contents: write

env:
  MISE_EXPERIMENTAL: "1"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Install mise
        uses: jdx/mise-action@v4

      - run: |
          npm ci
          npm run build
          npm publish --access public
        working-directory: flipt-client-react
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_REACT_API_KEY }}
