name: Package Ruby SDK
on:
  push:
    tags: ["flipt-client-ruby-**"]

permissions:
  contents: write
  id-token: write

env:
  RUBYGEMS_API_KEY: ${{ secrets.RUBYGEMS_API_KEY }}

jobs:
  build:
    uses: ./.github/workflows/package-ffi-sdks.yml
    with:
      sdks: ruby
      engine-tag: "latest"
    secrets: inherit
