name: Package Browser SDK
on:
  push:
    tags: ["flipt-client-browser-**"]

permissions:
  contents: write

env:
  NPM_API_KEY: ${{ secrets.NPM_API_KEY }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Sources
        uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: "1.21.3"
          check-latest: true
          cache: true

      - name: Install Dagger
        run: |
          cd /usr/local
          curl -L https://dl.dagger.io/dagger/install.sh | DAGGER_VERSION=$DAGGER_VERSION sh

      - name: Build Individual SDK(s)
        run: |
          dagger run go run ./build/wasm --sdks=browser --push=true
