name: Package WASM SDKs
on:
  workflow_call:
    inputs:
      sdks:
        description: "SDK(s) to build"
        type: string
        required: true
      tag:
        description: "Tag to use for SDK(s)"
        type: string
        required: false

permissions:
  contents: write

env:
  NPM_API_KEY: ${{ secrets.NPM_API_KEY }}
  MISE_EXPERIMENTAL: "1"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Install mise
        uses: jdx/mise-action@v4

      - name: Generate token
        id: generate_token
        uses: actions/create-github-app-token@v3
        with:
          app-id: ${{ secrets.FLIPT_RELEASE_BOT_APP_ID }}
          private-key: ${{ secrets.FLIPT_RELEASE_BOT_APP_PEM }}
          owner: ${{ github.repository_owner }}

      - name: Build Individual SDK(s)
        env:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
        run: |
          dagger run go run ./package/wasm --sdks=${{ inputs.sdks }} --push=true --tag=${{ inputs.tag }}
