name: Package JavaScript SDK
on:
  push:
    tags: ["flipt-client-js-**"]

permissions:
  contents: write

env:
  NPM_API_KEY: ${{ secrets.NPM_API_KEY }}

jobs:
  build:
    uses: ./.github/workflows/package-wasm-sdks.yml
    with:
      sdks: js
    secrets: inherit
