name: Release FFI Engine
on:
  push:
    tags: ["flipt-engine-ffi-v**"]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Create Release
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/flipt-engine-ffi-v')
        uses: actions/github-script@v7
        with:
          script: |
            const tag = context.ref.replace('refs/tags/', '');
            try {
              await github.rest.repos.getReleaseByTag({
                owner: context.repo.owner,
                repo: context.repo.repo,
                tag: tag
              });
              console.log(`Release for tag ${tag} already exists`);
            } catch (error) {
              if (error.status === 404) {
                console.log(`Creating new release for tag ${tag}`);
                await github.rest.repos.createRelease({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  tag_name: tag,
                  name: tag,
                  draft: false,
                  prerelease: false
                });
              } else {
                throw error;
              }
            }